language: java

jdk:
- oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

env:
  global:
    - secure: "qFj/+len1QO67SV/eZ/71dIqAxWymwmA+NsE/XGq0Txwb5qkwJTR7dpYxespAZpRnKvP3IcL6rHjB4afkJ4IVquUq9mc2qZDRQ+KDqTgHbTBcSdLGUrLAsqenjYdPl809O1RxaPaUpfapLWx3Zv7NxcLB2dJ1PZxZHpb+uqz/nGe7VoNNdnWOHDeAqYCWGUP08PebeDVD8NW8RhAncWGTvwDa1TDH74n8/8hSAhqDVbJvLpFWkG2xpuzPrSVS289lBSZ9CGSPerAjLaHFG8I1W9jDgNKD3liojVPXllktP3WS/gDFFjfRxeKSyMc/pot6tEMuk4SIpujThidYzhx7mcpV2bFtApLXiNY//9AJmqeQcEi9vxJWO68VYdNbK1UaAUYt9ZsqUuPqyycjISx1YdLhU4MkrrdbsPBudpERwu0bAudMXh91RvUSXDT1pPdvSkjo9P+LCD6e23nIFBX4tuTKIb9M98rWo7KzWLCjtYjJs12sCZ6PU9GgCM4+Y9yxEa19TMiHR+mymKnHJomitATPQJUnVCA89jUTObiV0C0NltdBRpqfObhBBbUkbS1h6pHaSDCNvE7RzCIZ2jSLKqNRGgr2Cd16WbIX/qLvSjzVKX4QDqU+e9/fLfIXufM8vAcuj5KfG6q/Hw6olD1wcvZR1PwpgI5NZCfDNaDagI="
    - secure: "qLiBtLbVZwQSYE5bC9JwnIJ9iV8cTzKc3LDCUFqeex4pKZmnmJfKTCpk5VeeyOh7uQHVmGgVtKcrHu2MN7Mvc6agQGUvXALEi+/a3q+k5JhC2sRiqDseRcvGapbVv3hU2+uGT5HGPW4xMjVVQoWwbw5BREZWOIy/kEC1OgjdWkyw7BmTtr+wXu9G2kyTKzzaIVIKyRxpwn+411dB5L3VtAO1YM335G4qotouhjIbQpsbCyniLhQxPnsZvUh323v4VSuOe8p7Vzm5n0f9tbnIH5K9rCKtz5cdPFqZEEgSKIRH23mkeWjq616jYj1KGVYkvGq91CyFVgnbQjPz6bI+VYiJcNjGv7B5OSd+lZXpiF7NPehprq3TBk3PAm9sskzfAaiC0QzRsGCZDdb1X61IxDQpSiH7IJCfOlYNpMAOezjPyLQqcSW0xoXLiMGyrUmeuUSJiHfhry/w7hs1TWzyJYiUfNf5GPnaCK3AHvAzTPeNr7Eruh9XYS45NK9Abih3lcnhKxaEd7w0rzAFsQTcn/9i9J5GibgnOKsmL+T31X9xRPt8VcbNFNhTdWTH19dxV7qzcaZmXr0WR4dvGk6xNsgmxcuRmtI58gYjDnDw3q41eUDW3FEITX/I5DF3sTiuRAh5erOUalN/GJqyLVR3u/6bHSzceXCnfj5OAx5g7/4="
    - secure: "IfX5R/H8m+0SpgTNFBk5fCAV4QGeMsaMDkiO672+uiJqW791fmA43bFzA5Z1AcQpSJpXNtcQ5Ot4E58JoLjwWjtx0mO4XIDhXTQ1WFFB+aA1E94iCq75+8q3ReCzAzMNkmO1EH2bYFmHVS70gKUPUi8+04TFMOKPyyrum4zdKC3IvLF1VBBkjha0bhAptn/gJKX10hm77c8AZ9j8lfcddx03g4CRrEZ9i8j82ulNgeFBAxlPQOsK1g9fqsPafEN5ir7vSL1gJlTOmklJ2I7APqvm53QMf6OKoaJ0OHxLBp7t6G6EuVxfYtz+vW0ebPIp/QUZ3kP7sRwoyGXESmiDFH0dAVV5NlOWtCnk3gRVNsaAIjOkT4L16CTNCcAoDJnsm4MVQpn8pCvFoygaAYSfluBdqOkEp69lpncgzM7Rz+AqERUxtvgKG4gSanDG46xPf8hgsGNxmDSbgB+0bE2uZeEhremjtRTkXS+THcJJM1a9ecWAUdQ/XDkQgphyQ2A6ODM3qDtc1dhDWIEXnfs2OQ8I92vvfZ1cYjDMux4IhytktmYBOIRAZvfSSFqWoQ35BaGDA8vvhjiD/FliNx7WyKR5+0FT1jh1uAXaWeMA7Yky4//1vr7QSsep40wWUbC5wQJVCchSenQqOlMAbhXnwqKRJXBm/S27ym1LrbxFPEY="
    - secure: "SuNh81eKE/suQ2xxgzLcoaM+TJ/IxJV4sPvag2hkg6g16NEYUObHRKI77DtBqKypnv2hTMcFCkcvHFV5kFN33+EG3M5AhBmQzT+rdDb6rJ82D4UqQDzWDF5m8qoe7l3/7ywe3wcfinAkJlgWqumOF+ECP4Rvt0sZy2wg2n+IOIOA1XxgXd6MJmbvZTChxdm3Vtgo0yc0yVdcqkEdDE0TJ8w/8n3jhQ/wHGsZkiLBct/kAmIh2H/ZuesEyZVwJP6rl6c0FIllrzry0ZvZh2ccuxTtpTq7/T5QpmMaxz0ogilkzI/yUTx01DkYla0rXAke9cXn/hEVqYoyQxbKXIwXSfGKKOpyhkpY+NWPqmWNkLrSkHTm1tfsBT7w1eznYP7o7ZRkYZp1R9sTcxGc2KaiEP27zxt6WTSjqDt1NZUGMxwJZsV6/W77dJRNyrZHxqczk3px6UorV2pIQGWmOyTn2gjwx6q5Y36tVSaVG3vQgmM9QnSQ23JMKZsTqRvmUx2V1qffwAgFHkN+y7jhTKyShck3NwyLi+w6MVSFwe895KM6naGV7C4TmPptySCuN0jnwjL0TiHE3ckSKEtwea3t+U/WFzGgeUGFfrL6wMI6EafjQ68xM3zWdPWh+IJWyaoZghyRW6gzLaL3AcRs8UZ8FKD+82kza5+lSPMHuu0zYQY="
    - secure: "k4sUvHYJo+05+UsqNCK3Mn0/3iAtUJsCDoveVfZfyahi023nf3f5ArGR9HHd1xIXRFgebn95V6vLnFxXcwDh8l6zz8hiA3XlQsN4IkL2quzK85GPeJUYxcRumJFO1GHEWZIe2C7gBnvyW9bB7KJ6PJRSZ0SFocnAwjMmMLSHsmnMvXGy2Xy5PIikKHMFQZjtl7YNSIkvc/dZ91zUT1EsG1HFtgP+22HgT+xdz50E6jzXAH+ClNT2buX6K5DaWOruIHKcif5V6/SC9QRmPd5t5DxYMsEirKlzFp7mNWuO7e66Rg3XSz31+OnJWfbfMV02DK4Hwej+WAhDj/k9Us6OG8yDUNVzcXnNT393wG3xdyl3H3Ix17wM1HHF/q1jaHPmx/jiDElUIYYQncwyznrMty8AfOF6W0h7pfYJmDbioLVlZm1lzRJik8W3OdkT/UgeFhTeBnEysh9B5hYCP2hjLpqBIgUiIrWPEe9ayufghkWcgJ7eMTgcsHQOqL1hYbNXvTSWSLJg3LxRygVeEiF8W0oTYbjZs16TZIQyG45qxmqUy1Vi9LyHBDdHDF44gI5z4xOh2ieBmTJ0YzesK1zn+lRDK2l8shUitp3/3Tj6R7iVQ1O6jRkie9n3nTvU05ewTSF979k6zVQhqZuuHR6/173c5HokdmZfCC3neXEYr8w="

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c8d9b2dce013e34dca96
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

before_install:
- if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then openssl aes-256-cbc -K $encrypted_b5bd0f53abc1_key -iv $encrypted_b5bd0f53abc1_iv -in scripts/travis-gpg-key.enc -out scripts/travis-gpg-key.dec -d; fi

install:
  - mvn --settings scripts/travis-maven-settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

sudo: false

script:
- scripts/build-project.sh

before_deploy:
  - cp scripts/travis-maven-settings.xml ~/.m2/settings.xml

deploy:
  - provider: releases
    api_key: ${GITHUB_TOKEN}
    file_glob: true
    #file:
    #  - core/target/agql-lib-core-*.jar
    #  - examples/target/agql-lib-examples-*.jar
    #  - protocols/supercell/clashofclans/webapi/target/agql-coc-webapi-*.jar
    #  - protocols/valve/csgo/webapi/target/agql-csgo-webapi-*.jar
    #  - protocols/valve/dota2/webapi/target/agql-dota2-webapi-*.jar
    #  - protocols/valve/source/query/target/agql-source-query-*.jar
    #  - protocols/valve/steam/master/target/agql-steam-master-*.jar
    #  - protocols/valve/steam/webapi/target/agql-steam-webapi-*.jar
    skip_cleanup: true
    on:
      tags: true
      repo: ribasco/async-gamequery-lib
  - provider: script
    script: scripts/deploy-project.sh
    skip_cleanup: true
    on:
     branch: master
     repo: ribasco/async-gamequery-lib

after_success:
- gpg --import scripts/travis-gpg-key.dec
- scripts/deploy-site.sh
# - mvn jacoco:prepare-agent jacoco:report coveralls:report

cache:
  directories:
    - '$HOME/.m2/repository'