language: java

jdk:
- oraclejdk8

env:
  global:
    # GITHUB_TOKEN
    - secure: "qFj/+len1QO67SV/eZ/71dIqAxWymwmA+NsE/XGq0Txwb5qkwJTR7dpYxespAZpRnKvP3IcL6rHjB4afkJ4IVquUq9mc2qZDRQ+KDqTgHbTBcSdLGUrLAsqenjYdPl809O1RxaPaUpfapLWx3Zv7NxcLB2dJ1PZxZHpb+uqz/nGe7VoNNdnWOHDeAqYCWGUP08PebeDVD8NW8RhAncWGTvwDa1TDH74n8/8hSAhqDVbJvLpFWkG2xpuzPrSVS289lBSZ9CGSPerAjLaHFG8I1W9jDgNKD3liojVPXllktP3WS/gDFFjfRxeKSyMc/pot6tEMuk4SIpujThidYzhx7mcpV2bFtApLXiNY//9AJmqeQcEi9vxJWO68VYdNbK1UaAUYt9ZsqUuPqyycjISx1YdLhU4MkrrdbsPBudpERwu0bAudMXh91RvUSXDT1pPdvSkjo9P+LCD6e23nIFBX4tuTKIb9M98rWo7KzWLCjtYjJs12sCZ6PU9GgCM4+Y9yxEa19TMiHR+mymKnHJomitATPQJUnVCA89jUTObiV0C0NltdBRpqfObhBBbUkbS1h6pHaSDCNvE7RzCIZ2jSLKqNRGgr2Cd16WbIX/qLvSjzVKX4QDqU+e9/fLfIXufM8vAcuj5KfG6q/Hw6olD1wcvZR1PwpgI5NZCfDNaDagI="
    # SONATYPE_USERNAME
    - secure: "qLiBtLbVZwQSYE5bC9JwnIJ9iV8cTzKc3LDCUFqeex4pKZmnmJfKTCpk5VeeyOh7uQHVmGgVtKcrHu2MN7Mvc6agQGUvXALEi+/a3q+k5JhC2sRiqDseRcvGapbVv3hU2+uGT5HGPW4xMjVVQoWwbw5BREZWOIy/kEC1OgjdWkyw7BmTtr+wXu9G2kyTKzzaIVIKyRxpwn+411dB5L3VtAO1YM335G4qotouhjIbQpsbCyniLhQxPnsZvUh323v4VSuOe8p7Vzm5n0f9tbnIH5K9rCKtz5cdPFqZEEgSKIRH23mkeWjq616jYj1KGVYkvGq91CyFVgnbQjPz6bI+VYiJcNjGv7B5OSd+lZXpiF7NPehprq3TBk3PAm9sskzfAaiC0QzRsGCZDdb1X61IxDQpSiH7IJCfOlYNpMAOezjPyLQqcSW0xoXLiMGyrUmeuUSJiHfhry/w7hs1TWzyJYiUfNf5GPnaCK3AHvAzTPeNr7Eruh9XYS45NK9Abih3lcnhKxaEd7w0rzAFsQTcn/9i9J5GibgnOKsmL+T31X9xRPt8VcbNFNhTdWTH19dxV7qzcaZmXr0WR4dvGk6xNsgmxcuRmtI58gYjDnDw3q41eUDW3FEITX/I5DF3sTiuRAh5erOUalN/GJqyLVR3u/6bHSzceXCnfj5OAx5g7/4="
    # SONATYPE_PASSWORD
    - secure: "PCmPE3kfR9jrLN+AifSdu/3w6MYmOsnFFD9kFS7svgdxnO2cJnJtlcXUT7Ndl4ezy29XYEo1NUA/YNLV0xL7JytvYZB7JtTT4U23spiM+eJvMEtQ71JkCHU2UNV02q4mcxMayTvPW3ocanYWK0Rnxcvy6IpGXNeZynoJg4s4DzTlRjRZGFdLzHQnxvepjxAsxMBUT68PXtJrvBhZhsXmSGLW6XghnPnntWBkpkHNMuX0LxzQJgxKLhVVy8XfeSpWcgnJo61p8YxRY8TLqt4TFfzCAgeeC+BH1Ccx4oQrhHhHvy96u6ez60azgOj/MZAI/5emIgpKyPo0eMBwkxIfvmqxzXkj3GZK2kIE8EifuD9Vwx0WuYXyj3K7mSVPG15Ib20gMRg9C+5SyPh2/3CKBcmWlHYMqUVTliX/62efBNJV8n9lNjHuM+vSU3mgheQe8S6Hm1oX5WAP89+5KfPGFvqsPlyyfvRDKWFRanc+3Y0Z111rck4XFZ2oBFj8v4LRHXipNoxSPBshKV38MDMBzH1XsLXa/9gZdSxSPyLDkPqeuLz++I/hNAVfJREEuoqzTmeyrmfDpph7yBIute3WX02om7geprMJmpsLsGbTDkvaDPc3okDyDwLskWbSqDXiU9v6FDNSAoiBqhg3JLfbNDEQBWr6vikJjjdAsY7oTFE="
    # COVERALL_TOKEN
    - secure: "SuNh81eKE/suQ2xxgzLcoaM+TJ/IxJV4sPvag2hkg6g16NEYUObHRKI77DtBqKypnv2hTMcFCkcvHFV5kFN33+EG3M5AhBmQzT+rdDb6rJ82D4UqQDzWDF5m8qoe7l3/7ywe3wcfinAkJlgWqumOF+ECP4Rvt0sZy2wg2n+IOIOA1XxgXd6MJmbvZTChxdm3Vtgo0yc0yVdcqkEdDE0TJ8w/8n3jhQ/wHGsZkiLBct/kAmIh2H/ZuesEyZVwJP6rl6c0FIllrzry0ZvZh2ccuxTtpTq7/T5QpmMaxz0ogilkzI/yUTx01DkYla0rXAke9cXn/hEVqYoyQxbKXIwXSfGKKOpyhkpY+NWPqmWNkLrSkHTm1tfsBT7w1eznYP7o7ZRkYZp1R9sTcxGc2KaiEP27zxt6WTSjqDt1NZUGMxwJZsV6/W77dJRNyrZHxqczk3px6UorV2pIQGWmOyTn2gjwx6q5Y36tVSaVG3vQgmM9QnSQ23JMKZsTqRvmUx2V1qffwAgFHkN+y7jhTKyShck3NwyLi+w6MVSFwe895KM6naGV7C4TmPptySCuN0jnwjL0TiHE3ckSKEtwea3t+U/WFzGgeUGFfrL6wMI6EafjQ68xM3zWdPWh+IJWyaoZghyRW6gzLaL3AcRs8UZ8FKD+82kza5+lSPMHuu0zYQY="
    # GPG_PASSPHRASE
    - secure: "Ud9+Autkny2dQXVCkpSKOnX3qxdPKUMzRisC3dRFUfPaC6hRxXmDPYgyFgBjYdU+45F6l5/ZrNzOCvXXuWvzwPEC3bP4VmX7H2Reuy/EGhGjYpIu55Cto0qkbQM2lerxGIYA46D4HQI+Dh7RGXBLxkk/P3uGSwnvSPFK/DR7fOgjAdDeV1E+EjXBwGe1chfZUDQU/yPILWq8RVW6pUmwkI/5ZUqrHZA3kNQzcoqOzphFMcyhAaUvGOO1oSsWX+TzqW0h3oncCdzRFB6tihMXHcLRziWBV8bOuEAKNflqIA4R3z/O8KCJQZha104D7oIz8Z+jPe3z9eg0ulcQI8AQCXz/rrV0fJJWTWeYYxis9wzBuSS1hiAfg+tjmxZpDADm/o4yeAD3Ia7Hg6v8p+Q7xrJY9RbKCtJ5PZe8v+yc2SDy8U2K4IA+BSfIq0henYtRQXdHL6Be9AL+wUEoPa35BWU6TJV+hlEkLSIm07TQz1raGUonTi3WqEfGEBZ/hWm2wqjQeF6D6o89ESC9NpPjC+a2IwjXoqo61ZAkSawL1IA8VI+Y+AlAFwmOIE00Kr/9gpP+d1iLqm/32vLNVcraWdKJusQ+74eufM2pT1KBKlnuIoZjY69sylBZxZzZRxOpvINwM+WgGZh9y/ANSiwlWKHgYA7ipAV1d0LVgs5C7lw="

install: true

sudo: false

before_install:
- openssl aes-256-cbc -K $encrypted_ed817947015b_key -iv $encrypted_ed817947015b_iv -in scripts/travis-gpg-key.enc -out scripts/travis-gpg-key.dec -d

script:
- scripts/build-project.sh

after_success:
#- git config credential.helper "store --file=.git/credentials"
#- echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials
- gpg --import scripts/travis-gpg-key.dec
- mvn clean jacoco:prepare-agent install jacoco:report coveralls:report
- scripts/deploy-project.sh
- scripts/deploy-site.sh

cache:
  directories:
    - '$HOME/.m2/repository'