language: java
jdk:
- oraclejdk8

secure: ZP1FWfLj1HQDrz2IFr9hzldtPIkEMA0+I7yxJfirjHG1HT+hnzwxZ8/o/QEBqQlgSFfLw1JVs26edYpogGCn+VOkWPUMPRgakHBkH8veuMaq2bIoVCjS/cRlLA9tsmN2zKBZ0OESM0XvAGpY/2JUjIbjvGUXe0JXyxQNfWyKh26wYk4y/eQPmBSb+PcZ/+f76989sAgS1ucOxxa5V7WdMXoNxVDcGDpy4kbBxsvikXF+5/w9+Qqb3l+tFcN2csyP2bGXqgVh0SJXRwn87UqoHt0UNFX8q+5W3bUNzWqjYjR3IjncHgaKDtUJg+3Z7J/ZhR4c9vjwz7PnOFjTaEIH8V0ljA2c3cWWt7wCMtGGw9niOWvxK2aV+IlYqFVO4gNneNohQyFaJ2TEELDJ9RWAISygSlz4buwBL08Sz8hZZLnz7yGIfJtgbCIrNvdZPUo6M8yfV54mhoIMueuZPO+BykGO3OWyROB1nAtoGLFfEKHYHnsnVztaP1Qx0viJkxQV46ZNqhhwKsbOjJEquWGCzsjjtK90gV0QH/i97Qs2YYukkxTjHHCZzSQkMQqrXPZmO0XzYjcXmFOzFDdLogl0xxXmnxPKtcWPFnd5e/sqaAKWSsvJn+/v3T2Qr53MzOUrVuNQ+9hSEy+pFNHLFWm7v5Z3iWBheUj72ed2gjieZII=

after_success:
- scripts/build-site.sh
- scripts/deploy-site.sh

cache:
  directories:
    - $HOME/.m2/repository